DROP_SEQ_LIST = 
{
	"DropCoinGold",
	"DropCoinSilver",
	"DropCoinCopper",
	"DropItemEgg",
	"DropItemChicken1",
	"DropItemChicken2",
	"DropItemFurits1",
	"DropItemFurits2",
	"DropItemFurits3",
	"DropItemPotionHP",
	"DropItemPotionMP",
	
	"DropItemBeewing",
	"DropItemBugshell",
	"DropItemBugsting",
	
	"DropItemBrawn",
	"DropItemMutton",
	
	"DropItemDrop_Acc_Shentianci",
	"DropItemDrop_Foot_Shentianci",
	"DropItemDrop_Hair_Shentianci",
	"DropItemDrop_Hand_Shentianci",
	"DropItemDrop_Lowbody_Shentianci",
	"DropItemDrop_Upbody_Shentianci",
	"DropItemDrop_Weapon_Shentianci",
	
	"DropItemDrop_Acc_Yueling",
	"DropItemDrop_Foot_Yueling",
	"DropItemDrop_Hair_Yueling",
	"DropItemDrop_Hand_Yueling",
	"DropItemDrop_Lowbody_Yueling",
	"DropItemDrop_Upbody_Yueling",
	"DropItemDrop_Weapon_Yueling",

	"DropItemDrop_Acc_Xiao",
	"DropItemDrop_Foot_Xiao",
	"DropItemDrop_Hair_Xiao",
	"DropItemDrop_Hand_Xiao",
	"DropItemDrop_Lowbody_Xiao",
	"DropItemDrop_Upbody_Xiao",
	"DropItemDrop_Weapon_Xiao",

	
	"DropItemLeather",
	"DropItemMushroomhead",
	"DropItemPlate",
	"DropItemPotionHp_1",
	"DropItemPotionHp_2",
	"DropItemPotionHp_3",
	"DropItemPotionMp_1",
	"DropItemPotionMp_2",
	"DropItemPotionMp_3",
	"DropItemPowderEL",
	"DropItemPowderEl_1",
	
	"DropItemCubicShentianci",
	"DropItemCubicXiao",
	"DropItemCubicYueling",
	"DropItemCubicEl",
	"DropItemCubicAriel",
	"DropItemCubicGrey",
	"DropItemCubicRStone",	
	
	"DropItemChocolate",
	
	"DropItemPouch_question",
	"DropItemUpgrade_Rock",

	"DropItem_Coin_copper",
	"DropItem_Coin_silver",
	"DropItem_Coin_gold",
	"DropItem_Bag1",
	"DropItem_Bag2",
	"DropItem_Bag3",
	"DropItem_Bag4",

	"DropItem_Sword",
	"DropItem_Wand",
	"DropItem_Bow",
	"DropItem_Body",
	"DropItem_Leg",
	"DropItem_Hand",
	"DropItem_Foot",
	"DropItem_Ring",
	"DropItem_Necklace",
	
	"DropItem_Stone1",
	"DropItem_Stone2",
	"DropItem_Stone3",

	"DropItem_Hp1",
	"DropItem_Hp2",
	"DropItem_Hp3",
	"DropItem_Hp4",
	
	"DropItem_Mp1",
	"DropItem_Mp2",
	"DropItem_Mp3",
        "DropItem_NanGua01",
	"DropItem_Zongzi01",
	"DropItem_Zongzi02",

	"DropItem_Scroll1",
	"DropItem_Scroll2",
	"DropItem_Scroll3",

	"DropItem_SkillBook1",
	"DropItem_SkillBook2",
	"DropItem_SkillBook3",
}

DROP_XFILE_LIST = 
{
	"item_Coin_gold.y",
	"item_Coin_silver.y",
	"item_Coin_copper.y",
	"Item_Egg.y",
	"Item_Chicken_1.y",
	"Item_Chicken_2.y",
	"Item_Fruits_1.y",
	"Item_Fruits_2.y",
	"Item_Fruits_3.y",
	"Item_PotionHP.y",
	"Item_PotionMP.y",
	
	"Item_Beewing.y",
	"Item_Bugshell.y",
	"Item_Bugsting.y",
	
	"Item_brawn.y",
	"Item_Mutton.y",
		
	"Item_Drop_Acc_Shentianci.y",
	"Item_Drop_Foot_Shentianci.y",
	"Item_Drop_Hair_Shentianci.y",
	"Item_Drop_Hand_Shentianci.y",
	"Item_Drop_Lowbody_Shentianci.y",
	"Item_Drop_Upbody_Shentianci.y",
	"Item_Drop_Weapon_Shentianci.y",

	"Item_Drop_Acc_Yueling.y",
	"Item_Drop_Foot_Yueling.y",
	"Item_Drop_Hair_Yueling.y",
	"Item_Drop_Hand_Yueling.y",
	"Item_Drop_Lowbody_Yueling.y",
	"Item_Drop_Upbody_Yueling.y",
	"Item_Drop_Weapon_Yueling.y",


	"Item_Drop_Acc_Xiao.y",
	"Item_Drop_Foot_Xiao.y",
	"Item_Drop_Hair_Xiao.y",
	"Item_Drop_Hand_Xiao.y",
	"Item_Drop_Lowbody_Xiao.y",
	"Item_Drop_Upbody_Xiao.y",
	"Item_Drop_Weapon_Xiao.y",
	
	"Item_Leather.y",
	"Item_Mushroomhead.y",
	"Item_Plate.y",
	"Item_PotionHp_1.y",
	"Item_PotionHp_2.y",
	"Item_PotionHp_3.y",
	"Item_PotionMp_1.y",
	"Item_PotionMp_2.y",
	"Item_PotionMp_3.y",
	"Item_PowderEL.y",
	"Item_PowderEl_1.y",
	
	"Item_Drop_Cubic.y",
	
	"Item_Chocolate.y",
	
	"Item_Pouch_question.y",
	"Item_Upgrade_Rock.y",

	"DropItem_Coin_copper.Y",
	"DropItem_Coin_silver.Y",
	"DropItem_Coin_gold.Y",
	"DropItem_Bag1.Y",
	"DropItem_Bag2.Y",
	"DropItem_Bag3.Y",
	"DropItem_Bag4.Y",

	"DropItem_Sword.Y",
	"DropItem_Wand.Y",
	"DropItem_Bow.Y",
	"DropItem_Body.Y",
	"DropItem_Leg.Y",
	"DropItem_Hand.Y",
	"DropItem_Foot.Y",
	"DropItem_Ring.Y",
	"DropItem_Necklace.Y",

	"DropItem_Stone1.Y",
	"DropItem_Stone2.Y",
	"DropItem_Stone3.Y",

	"DropItem_Hp1.Y",
	"DropItem_Hp2.Y",
	"DropItem_Hp3.Y",
	"DropItem_Hp4.Y",

	"DropItem_Mp1.Y",
	"DropItem_Mp2.Y",
	"DropItem_Mp3.Y",
	"DropItem_NanGua01.Y",
	"DropItem_Zongzi01.Y",
	"DropItem_Zongzi02.Y",

	"DropItem_Scroll1.Y",
	"DropItem_Scroll2.Y",
	"DropItem_Scroll3.Y",

	"DropItem_SkillBook1.Y",
	"DropItem_SkillBook2.Y",
	"DropItem_SkillBook3.Y",
}