  
 
  
GAME_OPTION_CURRENT = 
{ 
	-- GRAPHIC OPTION 
	AUTOSET_LEVEL		= 0, 
	GRAPHIC_UNIT		= OPTION_LEVEL["OL_HIGH"], 
	GRAPHIC_TEXTURE		= OPTION_LEVEL["OL_HIGH"], 
	GRAPHIC_MAP			= OPTION_LEVEL["OL_HIGH"], 
	GRAPHIC_EFFECT		= TRUE, 
	RESOLUTION_X		= 1024, 
	RESOLUTION_Y		= 768, 



	-- SOUND OPTION 
	SOUND			= TRUE, 
	MUSIC			= TRUE, 
	SOUND_VOLUME		= -1500, 
	MUSIC_VOLUME		= -1500, 
	


	-- OTHER OPTION 
	DYNAMIC_CAMERA		= TRUE, 
} 
