
GAME_OPTION_PRESET0 = { 	AUTOSET_LEVEL		= 0, 	GRAPHIC_UNIT		= OPTION_LEVEL["OL_HIGH"], 
	GRAPHIC_TEXTURE		= OPTION_LEVEL["OL_HIGH"], 
	GRAPHIC_MAP			= OPTION_LEVEL["OL_HIGH"], 
	GRAPHIC_EFFECT		= TRUE, 	RESOLUTION_X		= 1600, 	RESOLUTION_Y		= 1200, } 

GAME_OPTION_PRESET1 = { 	AUTOSET_LEVEL		= 1, 	GRAPHIC_UNIT		= OPTION_LEVEL["OL_MEDIUM"], 
	GRAPHIC_TEXTURE		= OPTION_LEVEL["OL_MEDIUM"], 
	GRAPHIC_MAP			= OPTION_LEVEL["OL_MEDIUM"], 
	GRAPHIC_EFFECT		= TRUE, 	RESOLUTION_X		= 1024, 	RESOLUTION_Y		= 768, } GAME_OPTION_PRESET2 = { 	AUTOSET_LEVEL		= 2, 	GRAPHIC_UNIT		= OPTION_LEVEL["OL_LOW"], 
	GRAPHIC_TEXTURE		= OPTION_LEVEL["OL_LOW"], 
	GRAPHIC_MAP			= OPTION_LEVEL["OL_LOW"], 
	GRAPHIC_EFFECT		= TRUE, 	RESOLUTION_X		= 1024, 	RESOLUTION_Y		= 768, } GAME_OPTION_PRESET3 = { 	AUTOSET_LEVEL		= 3, 	GRAPHIC_UNIT		= OPTION_LEVEL["OL_LOW"], 
	GRAPHIC_TEXTURE		= OPTION_LEVEL["OL_LOW"], 
	GRAPHIC_MAP			= OPTION_LEVEL["OL_LOW"], 
	GRAPHIC_EFFECT		= FALSE, 	RESOLUTION_X		= 640, 	RESOLUTION_Y		= 480, } 